# Generated by Django 2.0 on 2017-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedto',
            name='actualName',
            field=models.CharField(default='john doe', max_length=250),
        ),
    ]
