# Generated by Django 2.0 on 2017-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_assignedto_actualname'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedto',
            name='linked',
            field=models.BooleanField(default=False),
        ),
    ]
