# Generated by Django 2.0 on 2017-12-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_assignedto_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsToDo',
            fields=[
                ('cmd_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('pi_mac', models.CharField(max_length=250)),
            ],
        ),
    ]
