# Generated by Django 2.0 on 2017-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_commandstodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsLogs',
            fields=[
                ('mac', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('heat', models.CharField(max_length=250)),
                ('light', models.CharField(max_length=250)),
                ('moist', models.CharField(max_length=250)),
                ('rain', models.CharField(max_length=250)),
                ('water_lvl', models.CharField(max_length=250)),
                ('sync_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
