# Generated by Django 2.0 on 2017-12-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_sensorslogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorslogs',
            name='mac',
        ),
        migrations.AlterField(
            model_name='sensorslogs',
            name='sync_time',
            field=models.DateField(auto_now=True, primary_key=True, serialize=False),
        ),
    ]
