# Generated by Django 2.0 on 2017-12-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_sensorslogs_pi_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorslogs',
            name='sync_time',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
    ]
