# Generated by Django 2.0 on 2018-01-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20171228_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_door', models.BooleanField(default=False)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('avg_heat', models.IntegerField()),
                ('moist', models.IntegerField()),
                ('avg_light', models.CharField(max_length=250)),
                ('time_to_water', models.CharField(max_length=250)),
                ('priority', models.CharField(max_length=250)),
            ],
        ),
    ]
