# Generated by Django 2.0 on 2018-01-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_plantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantprofile',
            name='plant_name',
            field=models.CharField(default='unknown', max_length=250),
        ),
    ]
