# Generated by Django 2.0 on 2018-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_plantprofile_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='moist',
            field=models.CharField(max_length=250),
        ),
    ]
