# Generated by Django 2.0 on 2018-01-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20180103_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantprofile',
            name='out_door',
        ),
        migrations.AddField(
            model_name='plantprofile',
            name='location',
            field=models.CharField(default='outdoor', max_length=250),
        ),
    ]
